# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194onwLFhINNrtil0BUC55EWlrhrvzjbz
"""

import streamlit as st
import joblib
import pandas as pd

# Cargar modelo entrenado
modelo = joblib.load("/content/drive/MyDrive/DATASET/modelo_rf_final.pkl")

st.set_page_config(page_title="Bienestar Laboral", layout="centered")

st.title("🌱 Evaluación de Bienestar Laboral")
st.write("Esta aplicación usa Random Forest para predecir riesgos en salud mental.")

# Entradas del usuario
edad = st.number_input("Edad", 18, 100, 30)
horas_trabajo = st.slider("Horas de trabajo al día", 4, 16, 8)
estres = st.slider("Nivel de estrés (1 bajo - 10 alto)", 1, 10, 5)
satisfaccion = st.slider("Nivel de satisfacción laboral (1 bajo - 10 alto)", 1, 10, 5)

if st.button("🔍 Evaluar"):
    datos = pd.DataFrame({
        "edad": [edad],
        "horas_trabajo": [horas_trabajo],
        "estres": [estres],
        "satisfaccion": [satisfaccion]
    })

    pred = modelo.predict(datos)[0]
    probas = modelo.predict_proba(datos)[0]

    if pred == 1:
        st.error(f"⚠️ Riesgo detectado (Probabilidad: {probas[1]:.2f})")
    else:
        st.success(f"✅ Bajo riesgo (Probabilidad: {probas[0]:.2f})")

!pip install streamlit

# To run the Streamlit app, save the code in the cell above as a Python file (e.g., app.py)
# and then run the following command in your Colab terminal:
# !streamlit run app.py