# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194onwLFhINNrtil0BUC55EWlrhrvzjbz
"""

import streamlit as st
import joblib
import numpy as np

# ==========================
# Cargar modelo entrenado
# ==========================
modelo = joblib.load("/content/drive/MyDrive/DATASET/modelo_rf_final.pkl")

# ==========================
# Interfaz de la aplicación
# ==========================
st.title("📊 PHQ-9 App — Tamizaje de Depresión con Random Forest")
st.write("Esta aplicación permite realizar un tamizaje de depresión usando el cuestionario **PHQ-9**.")

st.markdown("---")
st.subheader("📋 Responde las 9 preguntas (valores de 0 a 3)")

# Entradas del usuario (PHQ-9)
inputs = []
for i in range(1, 10):
    val = st.number_input(
        f"Pregunta {i}",
        min_value=0,
        max_value=3,
        step=1,
        value=0
    )
    inputs.append(val)

# ==========================
# Botón de predicción
# ==========================
if st.button("🧾 Evaluar"):
    pred = modelo.predict([inputs])[0]

    st.markdown("### 🔎 Resultado del tamizaje:")
    if pred == 0:
        st.success("✅ Sin síntomas significativos de depresión.")
    elif pred == 1:
        st.warning("⚠️ Síntomas leves de depresión.")
    elif pred == 2:
            st.error("🚨 Síntomas moderados de depresión. Se recomienda seguimiento.")
    else:
        st.error("🚨 Síntomas severos de depresión. Buscar ayuda profesional.")

st.markdown("---")
st.caption("👩‍⚕️ Esta herramienta es de apoyo educativo desde Trabajo Social. No reemplaza la valoración profesional.")





"""After running the cells above, a public URL will be printed. Click on that URL to access your Streamlit application."""
