# -*- coding: utf-8 -*-
"""requirements.txt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JQTym5l0T3BFOP5d-uSUzpLFxAC4Fem
"""

!pip install streamlit
!pip install scikit-learn
!pip install pandas
!pip install joblib